# -*- coding: utf-8 -*-
"""parse_pirates_excel_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RASq0q5JGd3lyZlqKwRjg1A9qPTs_zZs
"""

import pandas as pd

excel_file_path = "Pirates CSG Master Spreadsheet.xlsx"
output_csv_path = "pirates.csv"

# Read all sheets into a dictionary of DataFrames
sheets_dict = pd.read_excel(excel_file_path, sheet_name=None)

# Create a list to hold each sheet's DataFrame
df_list = []

# Loop through each sheet and add a 'SheetName' column
for sheet_name, df in sheets_dict.items():
    df["SheetName"] = sheet_name
    df_list.append(df)

# Concatenate all DataFrames into one
combined_df = pd.concat(df_list, ignore_index=True)

# Write the combined DataFrame to CSV
combined_df.to_csv(output_csv_path, index=False)

print(f"All sheets combined into '{output_csv_path}' with {combined_df.shape[0]} rows and {combined_df.shape[1]} columns.")